### ISSUE TITLE
These are no FOSS apps - stop misleading people!!!

### ISSUE THREAD

**Issue by lunule** [DataDaoDe/awesome-foss-apps#10]
I just started to review the list, but it was enough to see the first two items to realize _you don't have a clue what FOSS means_.

**FOSS means FREE & Open-Source Software.**

Codesandbox has a freemium model.
Circle CI has a freemium model.
Almost everything these days have a freemium model, but this is not FOSS.

A great example of FOSS is Git Cola. Check their website - they don't have a pricing page, they don't try to get users with a free version that includes restricted functionality, _they offer the whole & full software for free_.

Another great example is a Linux distro, such as Bodhi, for instance. No pricing, no freemium, no restricted functionality, you get a full and wonderful software completely for free.

Just stop misleading people, what you're doing here is humiliating to the precious folks who spend their precious time contributing to **_really free_** software.

**Comment by DataDaoDe** [comment]
Thanks for your giving me your opinion on this. As far I am aware, the Codesandbox repository has a GNU License and Circle CI has an Eclipse license. And for me, if code/software has a FOSS license then I include it in this project, this doesn't mean the whole platform surrounding that software is free as in that it cost no money or that it doesn't have some revenue model built around it.  My understanding of what FOSS is is largely reflected in in the [Wikipedia Entry](https://en.wikipedia.org/wiki/Free_and_open-source_software), which is:

> Free and open-source software (FOSS) is software that is both free software and open-source software[a] where anyone is freely licensed to use, copy, study, and change the software in any way, and the source code is openly shared so that people are encouraged to voluntarily improve the design of the software.[3] This is in contrast to proprietary software, where the software is under restrictive copyright licensing and the source code is usually hidden from the users. 

I also consider free software to be a matter of liberty and not price. However, I don't want to get into a debate on what FOSS is or is not though. I am willing to accept you have your opinion and thats fine.

This repository is here so that other programmers can find non-trivial software application code that they can learn from and open source FOSS licenses permit that.
